FROM python:3.11-slim AS builder

WORKDIR /app
COPY app.py .
RUN pip install flask


# Etapa final
FROM python:3.11-slim

WORKDIR /app
COPY --from=builder /app /app

# ❗ Adicione esta linha abaixo!
RUN pip install flask

EXPOSE 8000
CMD ["python3", "app.py"]
